import {
  Transaction,
  Lead,
  Mentee,
  Client,
  TimeSlot,
  MessageTemplates,
  NotificationLog,
} from './types'

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Consultoria Tech Solutions',
    amount: 15000,
    date: '2026-03-20',
    entryDate: '2026-03-10',
    type: 'Receita',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Itaú',
    service: 'Consultoria',
    client: 'Tech Solutions SA',
    paymentMethod: 'PIX',
    performer: 'Eu',
    attachments: [
      { id: 'att1', name: 'Recibo_Pgto_TechSolutions.pdf', type: 'application/pdf', url: '#' },
    ],
  },
  {
    id: '2',
    description: 'Licença Software CRM',
    amount: 1200,
    date: '2026-03-22',
    entryDate: '2026-03-12',
    type: 'Despesa',
    status: 'Pendente',
    company: 'FM Academy',
    bank: 'Banco Nubank',
    category: 'Software',
    supplier: 'Salesforce',
    paymentMethod: 'Cartão de Crédito',
    performer: 'Terceiro',
  },
  {
    id: '3',
    description: 'Mentoria B2B - Alpha Ltda',
    amount: 8000,
    date: '2026-04-05',
    entryDate: '2026-03-15',
    type: 'Receita',
    status: 'Pendente',
    company: 'FM Consultoria',
    bank: 'Banco Itaú',
    service: 'Mentoria',
    client: 'Alpha Ltda',
    paymentMethod: 'Boleto',
    performer: 'Eu',
    paymentLink: 'https://pagamento.exemplo.com/123',
    attachments: [
      { id: 'att2', name: 'Boleto_Mensalidade_Alpha.pdf', type: 'application/pdf', url: '#' },
    ],
  },
  {
    id: '4',
    description: 'Marketing Ads',
    amount: 3500,
    date: '2026-03-25',
    entryDate: '2026-03-15',
    type: 'Despesa',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Nubank',
    category: 'Marketing',
    supplier: 'Facebook Ads',
    paymentMethod: 'Cartão de Crédito',
    performer: 'Terceiro',
  },
  {
    id: '5',
    description: 'Mentoria - João Silva - Parcela 1',
    amount: 1250,
    date: '2026-03-25',
    entryDate: '2026-03-01',
    type: 'Receita',
    status: 'Pendente',
    company: 'FM Academy',
    bank: 'Banco Nubank',
    service: 'Mentoria',
    client: 'João Silva',
    paymentMethod: 'PIX',
    performer: 'Eu',
    paymentLink: 'https://pagamento.exemplo.com/joao-silva-1',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Tech Solutions SA',
    value: 25000,
    targetDate: '2026-03-25',
    status: 'Geração de Proposta',
    phone: '5511999999999',
    email: 'contato@techsolutions.com',
    company: 'Grupo Flávio Moura',
  },
  {
    id: '2',
    name: 'João Silva (Mentoria)',
    value: 5000,
    targetDate: '2026-03-18',
    status: 'Negociando',
    phone: '5511888888888',
    email: 'joao@email.com',
    company: 'FM Academy',
  },
  {
    id: '3',
    name: 'Beta Corp',
    value: 40000,
    targetDate: '2026-04-10',
    status: 'Reunião de Diagnóstico',
    phone: '5511777777777',
    email: 'beta@betacorp.com',
    company: 'FM Consultoria',
  },
]

export const mockMentees: Mentee[] = [
  {
    id: '1',
    name: 'João Silva',
    company: 'FM Academy',
    contractValue: 5000,
    totalSessions: 10,
    status: 'Ativo',
    phone: '5511999999999',
    email: 'joao@email.com',
    sessions: [
      {
        id: 's1',
        date: '2026-03-01T10:00:00',
        duration: 60,
        discussion: 'Alinhamento de metas e objetivos pessoais.',
        tasks: 'Ler livro A, preencher planilha de orçamento.',
        status: 'Realizada',
      },
      {
        id: 's2',
        date: '2026-03-08T10:00:00',
        duration: 60,
        discussion: 'Acompanhamento da leitura e tarefas propostas.',
        tasks: 'Assistir curso X.',
        status: 'Falta',
      },
    ],
    attachments: [
      { id: 'att_m1', name: 'Contrato_Mentoria_Assinado.pdf', type: 'application/pdf', url: '#' },
      {
        id: 'att_m2',
        name: 'Planilha_de_Orçamento.xlsx',
        type: 'application/vnd.ms-excel',
        url: '#',
      },
    ],
    emailLogs: [
      {
        id: 'el1',
        date: '2026-03-01T09:00:00',
        type: 'Boas-vindas',
        subject: 'Bem-vindo à Mentoria!',
        status: 'Enviado',
      },
    ],
  },
  {
    id: '2',
    name: 'Diretoria Alpha Ltda',
    company: 'Grupo Flávio Moura',
    contractValue: 20000,
    totalSessions: 5,
    status: 'Concluído',
    phone: '5511888888888',
    email: 'contato@alpha.com',
    sessions: [
      {
        id: 's3',
        date: '2023-02-20T09:00:00',
        duration: 120,
        discussion: 'Diagnóstico corporativo inicial.',
        tasks: 'Levantamento de DRE.',
        status: 'Realizada',
      },
    ],
    emailLogs: [],
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Alpha Ltda',
    isB2B: true,
    companyName: 'Alpha Ltda',
    phone: '551133333333',
    email: 'contato@alpha.com',
    notes: 'Cliente prioritário. Contrato anual renovado em fev/2026.',
    contacts: [{ name: 'Carlos', role: 'CEO', phone: '5511911111111', email: 'carlos@alpha.com' }],
    status: 'Ativo',
    interactions: [
      {
        id: 'i1',
        date: '2026-03-01T10:00:00Z',
        note: 'Reunião de alinhamento trimestral concluída com sucesso.',
      },
    ],
    emailLogs: [],
  },
  {
    id: '2',
    name: 'João Silva',
    isB2B: false,
    phone: '5511888888888',
    email: 'joao@email.com',
    birthday: '1990-03-22',
    status: 'Ativo',
    interactions: [],
    emailLogs: [],
  },
]

export const mockTimeSlots: TimeSlot[] = [
  {
    id: 'ts1',
    date: '2026-03-25',
    time: '10:00',
    isBooked: false,
  },
  {
    id: 'ts2',
    date: '2026-03-25',
    time: '15:30',
    isBooked: true,
    menteeName: 'Carlos Beta',
    menteeEmail: 'carlos@beta.com',
    menteeCompany: 'Beta Corp',
  },
  {
    id: 'ts3',
    date: '2026-03-26',
    time: '14:00',
    isBooked: false,
  },
]

export const mockTemplates: MessageTemplates = {
  emailSubject: 'Lembrete de Mentoria: {{data_sessao}}',
  emailBody:
    'Olá {{nome_mentorado}},\n\nEste é um lembrete da nossa sessão de mentoria agendada para {{data_sessao}} às {{horario_sessao}}.\n\nLink da reunião: {{link_reuniao}}\n\nAté breve!',
  whatsappBody:
    'Olá {{nome_mentorado}}! Tudo bem? Passando para lembrar da nossa mentoria amanhã, {{data_sessao}} às {{horario_sessao}}. Link: {{link_reuniao}}',
  defaultMeetingLink: 'https://meet.google.com/abc-defg-hij',
}

export const mockNotificationLogs: NotificationLog[] = [
  {
    id: 'log1',
    menteeId: '1',
    menteeName: 'João Silva',
    sessionDate: '2026-03-01T10:00:00',
    channel: 'E-mail',
    status: 'Entregue',
    timestamp: '2026-02-28T10:00:00Z',
  },
  {
    id: 'log2',
    menteeId: '1',
    menteeName: 'João Silva',
    sessionDate: '2026-03-08T10:00:00',
    channel: 'WhatsApp',
    status: 'Enviado',
    timestamp: '2026-03-07T10:05:00Z',
  },
]
