import { Transaction, Lead, Mentee, Client } from './types'

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Consultoria Tech Solutions',
    amount: 15000,
    date: '2026-03-20',
    entryDate: '2026-03-10',
    type: 'Receita',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Itaú',
    service: 'Consultoria',
    client: 'Tech Solutions SA',
    paymentMethod: 'PIX',
    performer: 'Eu',
  },
  {
    id: '2',
    description: 'Licença Software CRM',
    amount: 1200,
    date: '2026-03-22',
    entryDate: '2026-03-12',
    type: 'Despesa',
    status: 'Pendente',
    company: 'FM Academy',
    bank: 'Banco Nubank',
    category: 'Software',
    supplier: 'Salesforce',
    paymentMethod: 'Cartão de Crédito',
    performer: 'Terceiro',
  },
  {
    id: '3',
    description: 'Mentoria B2B - Alpha Ltda',
    amount: 8000,
    date: '2026-04-05',
    entryDate: '2026-03-15',
    type: 'Receita',
    status: 'Pendente',
    company: 'FM Consultoria',
    bank: 'Banco Itaú',
    service: 'Mentoria',
    client: 'Alpha Ltda',
    paymentMethod: 'Boleto',
    performer: 'Eu',
  },
  {
    id: '4',
    description: 'Marketing Ads',
    amount: 3500,
    date: '2026-03-25',
    entryDate: '2026-03-15',
    type: 'Despesa',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Nubank',
    category: 'Marketing',
    supplier: 'Facebook Ads',
    paymentMethod: 'Cartão de Crédito',
    performer: 'Terceiro',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Tech Solutions SA',
    value: 25000,
    targetDate: '2026-03-25',
    status: 'Geração de Proposta',
    phone: '5511999999999',
    email: 'contato@techsolutions.com',
    company: 'Grupo Flávio Moura',
  },
  {
    id: '2',
    name: 'João Silva (Mentoria)',
    value: 5000,
    targetDate: '2026-03-18',
    status: 'Negociando',
    phone: '5511888888888',
    email: 'joao@email.com',
    company: 'FM Academy',
  },
  {
    id: '3',
    name: 'Beta Corp',
    value: 40000,
    targetDate: '2026-04-10',
    status: 'Reunião de Diagnóstico',
    phone: '5511777777777',
    email: 'beta@betacorp.com',
    company: 'FM Consultoria',
  },
  {
    id: '4',
    name: 'Mega Store',
    value: 12000,
    targetDate: '2026-03-30',
    status: 'Apresentação da Proposta',
    phone: '5511666666666',
    email: 'vendas@megastore.com',
    company: 'Grupo Flávio Moura',
  },
]

export const mockMentees: Mentee[] = [
  {
    id: '1',
    name: 'João Silva',
    company: 'FM Academy',
    contractValue: 5000,
    totalSessions: 10,
    status: 'Ativo',
    phone: '5511999999999',
    email: 'joao@email.com',
    sessions: [
      {
        id: 's1',
        date: '2023-11-01T10:00:00',
        duration: 60,
        discussion: 'Alinhamento de metas e objetivos pessoais.',
        tasks: 'Ler livro A, preencher planilha.',
      },
    ],
  },
  {
    id: '2',
    name: 'Diretoria Alpha Ltda',
    company: 'Grupo Flávio Moura',
    contractValue: 20000,
    totalSessions: 5,
    status: 'Concluído',
    phone: '5511888888888',
    email: 'contato@alpha.com',
    sessions: [
      {
        id: 's3',
        date: '2023-02-20T09:00:00',
        duration: 120,
        discussion: 'Diagnóstico corporativo inicial.',
        tasks: 'Levantamento de DRE.',
      },
    ],
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Alpha Ltda',
    isB2B: true,
    companyName: 'Alpha Ltda',
    phone: '551133333333',
    email: 'contato@alpha.com',
    contacts: [{ name: 'Carlos', role: 'CEO', phone: '5511911111111', email: 'carlos@alpha.com' }],
  },
  {
    id: '2',
    name: 'João Silva',
    isB2B: false,
    phone: '5511888888888',
    email: 'joao@email.com',
    birthday: '1990-03-22',
  },
]
