import { Transaction, Lead, Mentee, Client } from './types'

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Consultoria Tech Solutions',
    amount: 15000,
    date: '2026-03-20',
    type: 'Receita',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Itaú',
    service: 'Consultoria',
    performer: 'Eu',
  },
  {
    id: '2',
    description: 'Licença Software CRM',
    amount: 1200,
    date: '2026-03-22',
    type: 'Despesa',
    status: 'Pendente',
    company: 'FM Academy',
    bank: 'Banco Nubank',
    service: 'Software',
    performer: 'Terceiro',
  },
  {
    id: '3',
    description: 'Mentoria B2B - Alpha Ltda',
    amount: 8000,
    date: '2026-04-05',
    type: 'Receita',
    status: 'Pendente',
    company: 'FM Consultoria',
    bank: 'Banco Itaú',
    service: 'Mentoria',
    performer: 'Eu',
  },
  {
    id: '4',
    description: 'Marketing Ads',
    amount: 3500,
    date: '2026-03-25',
    type: 'Despesa',
    status: 'Pago',
    company: 'Grupo Flávio Moura',
    bank: 'Banco Nubank',
    service: 'Marketing',
    performer: 'Terceiro',
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Tech Solutions SA',
    value: 25000,
    targetDate: '2026-03-25',
    status: 'Geração de Proposta',
    phone: '5511999999999',
    email: 'contato@techsolutions.com',
    company: 'Grupo Flávio Moura',
  },
  {
    id: '2',
    name: 'João Silva (Mentoria)',
    value: 5000,
    targetDate: '2026-03-18',
    status: 'Negociando',
    phone: '5511888888888',
    email: 'joao@email.com',
    company: 'FM Academy',
  },
  {
    id: '3',
    name: 'Beta Corp',
    value: 40000,
    targetDate: '2026-04-10',
    status: 'Reunião de Diagnóstico',
    phone: '5511777777777',
    email: 'beta@betacorp.com',
    company: 'FM Consultoria',
  },
  {
    id: '4',
    name: 'Mega Store',
    value: 12000,
    targetDate: '2026-03-30',
    status: 'Apresentação da Proposta',
    phone: '5511666666666',
    email: 'vendas@megastore.com',
    company: 'Grupo Flávio Moura',
  },
]

export const mockMentees: Mentee[] = [
  {
    id: '1',
    name: 'João Silva',
    company: 'FM Academy',
    contractValue: 5000,
    totalSessions: 10,
    status: 'Ativo',
    phone: '5511999999999',
    email: 'joao@email.com',
    sessions: [
      {
        id: 's1',
        date: '2023-11-01T10:00:00',
        duration: 60,
        discussion: 'Alinhamento de metas e objetivos pessoais.',
        tasks: 'Ler livro A, preencher planilha.',
      },
      {
        id: 's2',
        date: '2026-10-15T14:30:00',
        duration: 60,
        discussion: 'Revisão da planilha financeira.',
        tasks: 'Aplicar método 50/30/20.',
      },
    ],
  },
  {
    id: '2',
    name: 'Diretoria Alpha Ltda',
    company: 'Grupo Flávio Moura',
    contractValue: 20000,
    totalSessions: 5,
    status: 'Concluído',
    phone: '5511888888888',
    email: 'contato@alpha.com',
    sessions: [
      {
        id: 's3',
        date: '2023-02-20T09:00:00',
        duration: 120,
        discussion: 'Diagnóstico corporativo inicial.',
        tasks: 'Levantamento de DRE.',
      },
      {
        id: 's4',
        date: '2023-03-05T09:00:00',
        duration: 120,
        discussion: 'Apresentação de resultados.',
        tasks: 'Ajustar escopo do projeto.',
      },
      {
        id: 's5',
        date: '2023-03-20T09:00:00',
        duration: 120,
        discussion: 'Definição de metas de vendas.',
        tasks: 'Revisão orçamentária para Q2.',
      },
      {
        id: 's6',
        date: '2023-04-10T09:00:00',
        duration: 120,
        discussion: 'Acompanhamento da implementação do CRM.',
        tasks: 'Treinar equipe comercial.',
      },
      {
        id: 's7',
        date: '2023-04-25T09:00:00',
        duration: 120,
        discussion: 'Sessão de encerramento.',
        tasks: 'Relatório final enviado aos diretores.',
      },
    ],
  },
]

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Alpha Ltda',
    isB2B: true,
    companyName: 'Alpha Ltda',
    phone: '551133333333',
    email: 'contato@alpha.com',
    contacts: [
      { name: 'Carlos', role: 'CEO', phone: '5511911111111', email: 'carlos@alpha.com' },
      { name: 'Ana', role: 'CFO', phone: '5511922222222', email: 'ana@alpha.com' },
    ],
  },
  {
    id: '2',
    name: 'João Silva',
    isB2B: false,
    phone: '5511888888888',
    email: 'joao@email.com',
    birthday: '1990-03-22',
  },
]
